name: deploy

env:
  SSH_USER: ${{ secrets.ZENBOX_USER }}
  SSH_HOST: ${{ secrets.ZENBOX_HOST }}

on:
  push:
    branches:
      - blog-hosting
jobs:
  deploy_go3:
    name: Deploy to Zenbox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host go2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Send files
        run: "rsync --delete -avO -e 'ssh -p 2233' ${{ env.RSYNC_FLAGS }} --exclude-from=${{ env.EXCLUDES }} ./ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DESTINATION }}"
        env:
          RSYNC_FLAGS: "" #--dry-run
          EXCLUDES: bin/rsync-excludes.txt
          SSH_HOST: ${{ secrets.ZENBOX_HOST }}
          DESTINATION: ${{ secrets.ZENBOX_PATH }}
